### ISSUE TITLE
New fields for INSTANCE_DB db type

### ISSUE THREAD

**Issue by ckx** [ckx/roguenarok#121]
We want to modify instance_db.yml to handle the following _additional_ fields for every instance, all of which should be exposed to NPCscript:

```
GameMode: FreeGrind
FloorMod: 1
Boss: 25007
BossRewardModifier: 500
SpawnGroupIds:
  1005: true
  1305: true
EndZone:
  X: 52
  Y: 55 
FlowerSpawnPoint:
  X: 103
  Y: 20
```

`FlowerSpawnPoint` should be optional, as it's only needed on MobArena instance types.

This will allow us to eliminate all the data currently in [tables_maps.txt](https://github.com/ckx/roguenarok/blob/master/roguenarok/npc/tables_maps.txt), and the boss reward modifier from [tables_spawngroups.txt](https://github.com/ckx/roguenarok/blob/master/roguenarok/npc/tables_spawngroups.txt)
